### ISSUE TITLE
1.20.1 backport is not functional

### ISSUE THREAD

**Issue by Not-February** [klikli-dev/theurgy-kubejs#6]
**Describe the bug**
If I try to load the [provided example file](https://github.com/klikli-dev/theurgy-kubejs/blob/00141adafafd183d4072754d856ca8ad3993dda1/runs/server/kubejs/startup_scripts/example.js), the game crashes on startup. It says it can't find the `derivativeTier` function.

**To Reproduce**
1. Install Theurgy KubeJS and all relevant prerequisite mods on 1.20.1 versions of the mod
2. Place the provided `example.js` file into the `kubejs/startup_scripts` folder
3. Launch game

**Expected behavior**
For the game to launch with a working example of custom sulfur/niter items

**Screenshots**
![image](https://github.com/user-attachments/assets/3212b404-566a-4dbc-8bc1-a48d52ceb836)

**System (please complete the following information):**
- Theurgy Version: 1.23.1
- OS: Windows 10
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 
Forge 47.3.0
Architectury 9.2.14
GeckoLib 4.4.9
KubeJS 2001.6.5-build.16
Modonomicon 1.77.3
Rhino 2001.2.3-build.6
Theurgy KubeJS 1.1.0

**Additional context**
[latest.log](https://github.com/user-attachments/files/18148081/latest.log)
[debug.log](https://github.com/user-attachments/files/18148082/debug.log)

**Comment by klikli-dev** [comment]
The API changed between 1.20.1 and 1.21.

You can find a working example by selecting 1.20.1 from the branch dropdown in the main repository view, or open the file directly here: https://github.com/klikli-dev/theurgy-kubejs/blob/version/1.20.1/run/kubejs/startup_scripts/example.js

**Comment by Not-February** [comment]
Oh, I see. Thanks for the quick response
